---
# tasks file for docker-registry
  - name: "docker login"
    docker_login:
      username: walid1919
      password: walid1919
  - name: "tag the image"
    docker_image:
      name: devops
      repository: walid1919/devops
      tag: latest
      push: yes
      source: local
